### ISSUE TITLE
Guidance on synchronizing across browser tabs

### ISSUE THREAD

**Issue by babichjacob** [joshnuss/svelte-local-storage-store#10]
Here's how I use the second argument of the `writable` creator to make the store update with storage events only as long as it has at least one subscriber:

https://github.com/babichjacob/svelte-localstorage/blob/fb04f7cdfeabb1f42e566b0cebca610893f5cc27/projects/svelte-localstorage/base.js#L13-L26

Let me know if you have any questions.

**Comment by joshnuss** [comment]
that's exactly what's needed! 

Thanks Jacob :clap: 

I will open a PR

**Comment by joshnuss** [comment]
It's been merged. Published in [v.0.2.0](https://www.npmjs.com/package/svelte-local-storage-store).

Thanks again for providing the solution. :raised_hands:
