### ISSUE TITLE
The documentation feels incomplete

### ISSUE THREAD

**Issue by Mys7erio** [joshnuss/svelte-local-storage-store#103]
This library could use some more documentation to make it more clear on how to use stores to retrieve data from objects.

**Comment by joshnuss** [comment]
Hi @Mys7erio,

Was there something specific you running into.

I tried to balance keeping docs short, so people don't have to read a lot.

Maybe the repo should have example code? Would that be helpful?

**Comment by Mys7erio** [comment]
Yes, more code showing how to retrieve data would be a nice addition to the documentation.  If added, it would help people who were in the same situation as me.

I was trying to access the attribute of an object but I wasn't able to. It took me some time but I eventually figured out how to do it.

**Comment by joshnuss** [comment]
I feel the Readme is already showing how to read from stores. Since the API is identical to all Svelte stores, I hesitate to make people read docs when nothing's different.

I'm going to close the issue for now, but if I hear more requests about docs, I'll definitely revisit this decision.
