### ISSUE TITLE
Open to contributing to our project?

### ISSUE THREAD

**Issue by endigo9740** [joshnuss/svelte-local-storage-store#104]
Hi Josh, my name is Chris. I'm the creator of Skeleton, an open source UI library for Svelte + Tailwind:

https://skeleton.brainandbonesllc.com/

Our library aims to provide a means to handle common UI and components for any kind of Svelte project. However, some of key features we are adding utilize local storage persistence via a Svelte Store. Such as persisting the currently selected theme to preview on our documentation site.

In fact, I had created a ticket with the goal in mind of recreating something like this:

https://github.com/Brain-Bones/skeleton/issues/283

However, after reviewing your project, I think we would be hard pressed to create something better. We would literally just be reinventing the wheel at this point. And for a small open source project that time may be better spent elsewhere. So is there any chance you would be willing to contribute a version of this to our project? We could put it use immediately for our internal site, as well as provide it as a built-in "utility" feature for end users.

I see a couple ways to go about this:

- Point users towards your repo and advise them to install from NPM directly as you describe. It would then be treated as a third party dependency. This drives more traffic to your project, but may provide a bigger barrier of entry for some folks.
- Package and embed a version of this directly within Skeleton, as is, so it's available by default to anyone using the library. This would provide the lowest barrier of entry and probably foster more use.

I'd obviously ensure we give you proper attribution and link to any resources you wish (this repo, etc).

Please let me know if you would be open to this, because thing freaking rocks! :)

**Comment by joshnuss** [comment]
Hi Chris,

Your project looks super cool!

Of course, feel free to integrate this package any way you'd like. This repo is MIT license so you are free to copy if you'd like, or add it as a dependency.

I think if you go the dependency route, the advantage is receiving updates (though this package is pretty stable and no major new features are planned), and if your user's don't use it, it wouldn't add anything to the final bundle since it would be tree-shaken.

I'll close the issue for now, but feel free to drop a line if you have any more questions or run into anything,

**Comment by endigo9740** [comment]
Awesome, I saw the license but I just wanted to make sure you were cool with the use case.

I agree with keeping up up to date, but honestly it looks fairly feature complete for our intended use cases. Me and our other contributors will make a note to keep an eye on this. And obviously feel free to ping us if you make major changes and are willing/able. A simple GitHub ticket would be enough to inform us.

Also, I did want to offer you the opportunity to contribute it yourself if you wish. No pressure, but then you would get proper contribution through GitHub, and a small shoutout and link on our homepage. But completely understand if you don't have time! I have no problem handling this asap.

OSS is all about collaboration, so let us know if there's anything else we can help you with on our side as well. Either way thanks for the help!

**Comment by joshnuss** [comment]
Thanks Chris, appreciate you checking in.

It's totally fine to copy, if you want to mention where you got it, or leave a comment in the source file. That's totally fine, but not obligated.

Honestly, none of these ideas are mine, they rely on the work of others, so happy to see others make use of it.

And best of luck with your project!
