### ISSUE TITLE
Allow using sessionStorage

### ISSUE THREAD

**Issue by janosh** [joshnuss/svelte-local-storage-store#111]
Could the [`Storage`](https://developer.mozilla.org/docs/Web/API/Storage) object be made configurable? Need to store something to [`sessionStorage`](https://developer.mozilla.org/docs/Web/API/Window/sessionStorage) instead of `localStorage`.

**Comment by joshnuss** [comment]
I believe the API for both are similar, so I'd be open to accepting a PR.

Though I wonder if the repo name should change then.

**Comment by janosh** [comment]
The API is indeed identical afaik. The only difference is `sessionStorage` is cleared when the page session ends.

> Though I wonder if the repo name should change then.

GH automatically setups up URL forward so changing the repo name would be easy. NPM is a problem though.

**Comment by joshnuss** [comment]
Could always add a deprecation warning post-install, if the package name
changes.
