### ISSUE TITLE
handle invalid json

### ISSUE THREAD

**Issue by BSN4** [joshnuss/svelte-local-storage-store#141]
i'm not sure why but sometime keys set to `undefiend` and it can't be json parsed so app crash , i traced source code back to:

  ```js
  if (json) {
        set(<T>serializer.parse(json))
}
```

try/catch maybe?

**Comment by BSN4** [comment]
i patched npm package with try/catch and seems did the trick

**Comment by joshnuss** [comment]
Hi @BSN4,

Was the key set to `undefined` on purpose? Usually calling `localStorage.getItem()` on an non-existing key would return a `null`, which the above code path should handle OK.

**Comment by BSN4** [comment]
no, but i set it on purpose to test it, and only way to fix the issue is wrapping the json parse with try/catch

**Comment by joshnuss** [comment]
hmm, because if `json` is `undefined`, the `if` statement main branch should not execute

```javascript
if (json) {
     // will not execute if json = undefined
     set(<T>serializer.parse(json))
}
```

**Comment by joshnuss** [comment]
If you can share the stack trace of the error, that might be helpful too

**Comment by BSN4** [comment]
yeah thats the logical thing but not sure why it will execute , i'm on latest node (v19.7.0), svelte (v3.54.0) , and latest svelte-local-storage-store

**Comment by BSN4** [comment]
@joshnuss `undefined` coming from the localStorage treated like string thats the only explanation

**Comment by joshnuss** [comment]
I see, the store must have be set to `undefined`, which causes `JSON.stringify(undefined)` and the result is saved as a string `'undefined'`

A possible solution is to use [`devalue`](https://www.npmjs.com/package/devalue) as the serializer, since it supports `undefined`

Example:

```javascript
import * as devalue from 'devalue'

// third parameter is options.
export const preferences = persisted('local-storage-key', 'default-value', {
  serializer: devalue
})
```
