### ISSUE TITLE
Add a warning in the readme regarding not using this to store sensitive data related stuff

### ISSUE THREAD

**Issue by kemoycampbell** [joshnuss/svelte-local-storage-store#147]
Some individuals without security backgrounds might assume that they can use this to "persist" data that may be sensitive. I think you should add a warning that the library uses local storage and sessionStorage which are not recommended for storing sensitive data due to their vulnerability to Cross-Site Scripting (XSS) Attacks. Other than that,  great library.

**Comment by joshnuss** [comment]
Hi @kemoycampbell,

Totally agree that local storage should never be used to store sensitive data like passwords or api keys.

But I'm not sure if I should put a disclaimer, or expect that folks know what they're doing.

The challenge with disclaimers is, there are many other things that could be pointed out, ie local storage is a client side technology that cannot be accessed server side, local storage persists across sessions and session storage is cleared when the browser is closed.

I feel it is a more general issue with local storage and not specific to this library.

Hope that's OK! Let me know if you have any further concerns
