### ISSUE TITLE
Lib not working with Blob data

### ISSUE THREAD

**Issue by forna** [joshnuss/svelte-local-storage-store#148]
The lib is not working when using Blobs.
I set the value in one page and in the next page the value is gone.
It works correctly if instead of Blob I use a String or an Int.

I write to the browser console in the page where the store is set:

![image](https://user-images.githubusercontent.com/1431006/230789218-8fd4f4c9-fe3f-4e84-8163-d9980c5d8c5a.png)

Then in the next page I try to retrieve the value and it is empty:

![image](https://user-images.githubusercontent.com/1431006/230789516-af5f060a-8420-4345-8442-2a58de15e2f5.png)

I have prepared an example to show the issue:

**src/lib/store.js:**
```
import { persisted } from "svelte-local-storage-store"
export const store = persisted("sessionStore",
    { blobStore: Blob },
    {storage: "local"})  
```

**src/routes/+page.svelte:**
```
<script>
    import {store} from "$lib/store.js"
    const obj = { hello: "world" }
    const blob = new Blob([JSON.stringify(obj, null, 2)], {type: "application/zip"})
    store.set({"blobStore": blob})
    console.log($store.blobStore)
</script>
<a href ="/destination">Click me!</a>
```

**src/routes/destination/+page.svelte:**
```
<script>
    import {store} from "$lib/store.js"
    console.log($store.blobStore)
</script>

```

**Comment by joshnuss** [comment]
Hi @forna,

This library uses `JSON.stringify()` under the hood to serialize data. But you can customize it by passing the `serializer` option.

There's an example in the readme.
