### ISSUE TITLE
Suggestion: Convert runtime deprecation notice to TS `@deprecated` annotation

### ISSUE THREAD

**Issue by EdricChan03** [joshnuss/svelte-local-storage-store#184]
Imo, converting the following `console.warn` deprecation notice to use TSDoc's `@deprecated` annotation would probably help surface the deprecation notice to end users without having to use it in the first place:

https://github.com/joshnuss/svelte-local-storage-store/blob/34b1994bd22180d704d7629938e9b27936aa375e/index.ts#L26

The function's code is stripped in the resulting generated type definitions, so it's hard to tell that it's actually deprecated:

```ts
// ...

declare function writable<T>(key: string, initialValue: T, options?: Options<T>): Writable<T>;
declare function persisted<T>(key: string, initialValue: T, options?: Options<T>): Writable<T>;

export { persisted, writable };
```

Something like the following should persist in the resulting definitions file:

```ts
/** @deprecated Use `persisted` instead */
export function writable(...)
```

**Comment by joshnuss** [comment]
Hi @EdricChan03 ,

Thanks for the suggestion!

I've opened a PR #185
