### ISSUE TITLE
writable is an awkward name

### ISSUE THREAD

**Issue by weepy** [joshnuss/svelte-local-storage-store#23]
IMHO at least ... because it makes it inconvenient to mix with the canonical svelte/store writable.

**Comment by joshnuss** [comment]
Thanks for the feedback.

es6 imports do support aliases:

```javascript
import { writable as localStorageStore } from 'svelte-local-storage-store'
```

so I'm not sure it's worth changing the name and deprecating, it will cause a lot of work for very little return. Maybe in a future version if there is are some big changes, I'll consider renaming it.

**Comment by weepy** [comment]
Well You could export both writable and writableLocalStorage. But yeah
minor really

**Comment by joshnuss** [comment]
Fair point
