### ISSUE TITLE
Clarify the difference between set and update

### ISSUE THREAD

**Issue by richarddavenport** [joshnuss/svelte-local-storage-store#4]
Thanks for this package. I'm seeing that `set` calls the internal writeable store's set method, but doesn't appear to update localstorage. Maybe I'm missing something. Could you clarify the intentions of each method (`set` vs `update`). They appear to do the same thing (replace the entire object in the state) but one replaces the in-memory object and the other the localstorage.

Thanks again!

**Comment by richarddavenport** [comment]
Well, I just read the code again and realized the `this.set`. I'm tracking now... How open are you to PR's?

**Comment by joshnuss** [comment]
@richarddavenport open to PRs!

The difference between `update()` and `set()`:

- `set` completely replaces the entire state.
- `update` provides the previous state, and then completely replaces the entire state.

This is in line with what svelte's `writable` API does. The only difference here is `update` must replace everything, because there's no way to partially update a value in `localStorage`.

**Comment by richarddavenport** [comment]
Just curious if you'd be open to partial updates?

**Comment by joshnuss** [comment]
Sure, but how would you do it? 

Doesn't the whole value have to be serialized to update `localStorage`?

**Comment by richarddavenport** [comment]
Well, I just started writing a pretty long reply and then I discovered that NGXS's state operators will work out of the box. Really interesting... NGXS has this concept of [state operators](https://www.ngxs.io/advanced/operators). [Here is the patch operator.](https://github.com/ngxs/store/blob/master/packages/store/operators/src/patch.ts)

State operators follow a simple signature
```
type StateOperator<T> = (existing: Readonly<T>) => T;
```

The `patch` operator works like this:
```
import { patch } from "@ngxs/store/operators";
import { writable } from "svelte-local-storage-store";
export const preferences = writable("preferences", {
  theme: 'dark',
  pane: '50%',
});

preferences.update(patch({
  theme: 'light',
})
```
And now just one (or more!) of my keys is updated.

**Comment by joshnuss** [comment]
I think you could just write:

```javascript
preferences.update(prefs => {
  prefs.theme = 'light'
  return prefs
})
```

But I think I understand the issue now. We shouldn't need to `return` anything from the callback. We should be able to mutate the current state inside the callback, like this:

```javascript
// no return, prefs is mutated
preferences.update(prefs => prefs.theme = 'light')
```

So yeah, that would be a useful PR

**Comment by richarddavenport** [comment]
Your first statement is correct, but the second is not. The patch operator doesn't mutate. However, the benefit comes when nesting changes and/or siblings. 

```
preferences.update(patch({
  someProp: patch({nestedProp: true}),
  anotherProp: patch({ nestedProp1: 'string value', nestedProp2: [...] })
})
```
In any case, I think I've realized that the ngxs state operators just work since the method signature is the same.

I'm going to see If I can pull those out and we could use them by themselves.

**Comment by abbychau** [comment]
could you put this to readme?

**Comment by joshnuss** [comment]
@abbychau can you clarify what you feel is missing from the readme?

**Comment by abbychau** [comment]
> @abbychau can you clarify what you feel is missing from the readme?

The difference between set and update .

**Comment by joshnuss** [comment]
They operate the same way as Svelte's `writable` store.

Did you encounter something confusing about them? (Would help me understand the issue better)
