### ISSUE TITLE
not working with SvelteKit

### ISSUE THREAD

**Issue by pjebs** [joshnuss/svelte-local-storage-store#56]
When SvelteKit is running local dev server, using `svelte-local-storage-store` gives error: `Cannot read property 'length' of undefined`.

I presume it's because LocalStorage is not available on server.
Or perhaps the initial value of the writable store is not properly returned by the store when run on node.

**Comment by joshnuss** [comment]
Hi,

It should work server side,

Can you share the stack trace?

**Comment by joshnuss** [comment]
By working server side, I mean it should not cause an error.

But Local Storage is a client-side browser API, so on the server it should return the default value of the store. Please advise if you are seeing a different behavior.

**Comment by pjebs** [comment]
I'll get the stack trace in a few days time. I can't use my computer at the moment.

**Comment by pjebs** [comment]
Is this library meant to be a drop in replacement for `'svelte/store'`? i.e. if the app worked perfectly before, it should work perfectly with this library after changing the import path.

**Comment by joshnuss** [comment]
Yes, it's a drop in replacement.
But you can't change the store's value server-side, because the local
storage API it's client side only.

**Comment by joshnuss** [comment]
Let me know if this is still an issue, or if it can be closed

**Comment by pjebs** [comment]
All good!
